<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-C1SS90L" ignored="0" name="Default test" tests="1" failures="1" timestamp="2022-04-11T19:49:33 IST" time="10.409" errors="0">
  <testcase name="TimeOut" time="10.214" classname="com.testNG_Project.Expected_Exception">
    <failure type="org.testng.TestException" message="
Expected exception of any of types [class com.testNG_Project.Expected_Exception, class org.openqa.selenium.TimeoutException] but got org.testng.internal.thread.ThreadTimeoutException: Method com.testNG_Project.Expected_Exception.TimeOut() didn&amp;apos;t finish within the time-out 10000">
      <![CDATA[org.testng.TestException: 
Expected exception of any of types [class com.testNG_Project.Expected_Exception, class org.openqa.selenium.TimeoutException] but got org.testng.internal.thread.ThreadTimeoutException: Method com.testNG_Project.Expected_Exception.TimeOut() didn't finish within the time-out 10000
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method com.testNG_Project.Expected_Exception.TimeOut() didn't finish within the time-out 10000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
... 22 more
]]>
    </failure>
  </testcase> <!-- TimeOut -->
</testsuite> <!-- Default test -->
